name: Flask CI

on: push

jobs:
  build:
    env:
      PORT: 8000
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest test.py

      - name: Run tests and generate XML report
        run: |
          python -m pytest -k test.py --junitxml=test-reports/test-results.xml

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: test-reports
